# Generated by Django 4.2.7 on 2024-03-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=100)),
                ('parliamentary_constituency', models.CharField(max_length=100)),
                ('assembly_constituency', models.CharField(max_length=100)),
            ],
        ),
    ]
