# Generated by Django 4.2.7 on 2024-03-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.AddField(
            model_name='voter',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='voter_pictures/'),
        ),
    ]
