# Generated by Django 4.2.7 on 2024-03-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_dob_voter_date_of_birth_voter_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
